# Site settings
title: Paul Rayner's Blog
email: paul@virtual-genius.com
description: > # this means to ignore newlines until "baseurl:"
  Paul Rayner's blog on DDD, BDD and agile.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thepaulrayner.com" # the base hostname & protocol for your site
twitter_username: thepaulrayner
github_username:  paulrayner

# Build settings

# Use same GitHub style syntax highlighting that Octopress enables by default
markdown: redcarpet

# Maintain permalinks in migration of posts from Octopress
permalink: /blog/:year/:month/:day/:title/

# Add support for AsciiDoc posts using Asciidoctor
gems:
  - jekyll-asciidoc