# Site settings
title: Leading by Design
email: paul@virtualgenius.com
description: Paul Rayner's blog on software design and process
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thepaulrayner.com" # the base hostname & protocol for your site
twitter_username: thepaulrayner
github_username:  paulrayner

# Build settings

# Use kramdown for GitHub Pages compatibility
markdown: kramdown
highlighter: rouge

# Maintain permalinks in migration of posts from Octopress
permalink: /blog/:year/:month/:day/:title/

# Jekyll 4.x uses 'plugins' instead of 'gems' 
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge

# AsciiDoc configuration removed - no longer needed

# Keep legacy post directories during builds
keep_files: [
  "about",
  "agility-is-a-skill", 
  "bdd-is-a-centered-rather-than-a-bounded-community",
  "cloud-strategy-design-and-automation",
  "design-is-difficult-design-quotes-part-4",
  "dont-give-your-customers-what-they-ask-for",
  "eventstorming-team-flow",
  "good-design-is-people-centered-design-quotes-part-5",
  "leanux-my-notes",
  "persisting-value-objects", 
  "plotting-paths-to-cloud-migration",
  "realtime-retro-eddd",
  "the-design-process-design-quotes-part-2",
  "value-objects-and-immutability",
  "what-is-design-design-quotes-part-1",
  "why-design-design-quotes-part-3",
  "blog",
  "tags",
  "archive.html",
  "legacy-index.html",
  "legacy-feed.xml"
]

exclude: ['README.adoc', 'Gemfile.lock', 'Gemfile', '*.sh', vendor, '_posts/*.adoc', 'copy_legacy_properly.sh']